project:
  type: website
  output-dir: docs  # Output to /docs for GitHub Pages

website:
  open-graph: true
  title: "Ally C. Hinton"
  site-url: https://allyhinton.github.io
  repo-url: https://github.com/allyhinton/allyhinton.github.io
  favicon: assets/images/uvm.ico

  navbar:
    style: "floating"
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: CV.pdf
        text: CV
      - href: Resume.pdf
        text: Resume
      - href: publications.qmd
        text: Publications
    search: true
    pinned: true

format:
  html:
    theme: spacelab
    toc: true
    smooth-scroll: true
    html-math-method: katex
    include-in-header:
      - includes.html
    footnotes-hover: false
    code-fold: true
    grid:
      body-width: 1100px